tildes y puntos arreglados
jonacf/HyperBlog pull request #1
Opened 2021-05-15 22:00 UTC by jonacf

No debimos pasar este error a main.

2021-05-15 22:29 UTC, Estrellacf requested changes
En vez de usar tildes directas, usa entidades HTML

2021-05-15 22:55 UTC, jonacf commented
Cambios hechos. Por favor, haz el merge.

2021-05-15 22:59 UTC, Estrellacf reviewed
Excelente! Eso era.

2021-05-15 23:02 UTC, Estrellacf approved these changes
Aprobado!

2021-05-15 23:06 UTC, merged

2021-11-10 21:49 UTC, jonacf reviewed
asdwa